{{- if and .Values.backend.enabled .Values.backend.secret.create (not .Values.backend.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gait.backend.secretName" . }}
  labels:
    {{- include "gait.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secret.values }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
